### ISSUE TITLE
Run time error

### ISSUE THREAD

**Issue by raghu1082** [KernelCrap/android-dlna#2]
Am not able to run this code. am getting error as show below, kindly please help me.

06-14 23:45:52.326: E/AndroidRuntime(6903): java.lang.NoClassDefFoundError: org.eclipse.jetty.server.Server
06-14 23:45:52.326: E/AndroidRuntime(6903): 	at org.fourthline.cling.transport.impl.jetty.JettyServletContainer.resetServer(JettyServletContainer.java:165)
06-14 23:45:52.326: E/AndroidRuntime(6903): 	at org.fourthline.cling.transport.impl.jetty.JettyServletContainer.<init>(JettyServletContainer.java:57)
06-14 23:45:52.326: E/AndroidRuntime(6903): 	at org.fourthline.cling.transport.impl.jetty.JettyServletContainer.<clinit>(JettyServletContainer.java:55)
06-14 23:45:52.326: E/AndroidRuntime(6903): 	at org.fourthline.cling.android.AndroidUpnpServiceConfiguration.createStreamServer(AndroidUpnpServiceConfiguration.java:110)
06-14 23:45:52.326: E/AndroidRuntime(6903): 	at org.fourthline.cling.transport.RouterImpl.startAddressBasedTransports(RouterImpl.java:427)
06-14 23:45:52.326: E/AndroidRuntime(6903): 	at org.fourthline.cling.transport.RouterImpl.enable(RouterImpl.java:132)
06-14 23:45:52.326: E/AndroidRuntime(6903): 	at org.fourthline.cling.android.AndroidRouter.enable(AndroidRouter.java:92)
06-14 23:45:52.326: E/AndroidRuntime(6903): 	at org.fourthline.cling.UpnpServiceImpl.<init>(UpnpServiceImpl.java:87)
06-14 23:45:52.326: E/AndroidRuntime(6903): 	at org.fourthline.cling.android.AndroidUpnpServiceImpl$1.<init>(AndroidUpnpServiceImpl.java:54)
06-14 23:45:52.326: E/AndroidRuntime(6903): 	at org.fourthline.cling.android.AndroidUpnpServiceImpl.onCreate(AndroidUpnpServiceImpl.java:54)
06-14 23:45:52.326: E/AndroidRuntime(6903): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3148)
06-14 23:45:52.326: E/AndroidRuntime(6903): 	at android.app.ActivityThread.access$1900(ActivityThread.java:177)
06-14 23:45:52.326: E/AndroidRuntime(6903): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1531)
06-14 23:45:52.326: E/AndroidRuntime(6903): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-14 23:45:52.326: E/AndroidRuntime(6903): 	at android.os.Looper.loop(Looper.java:145)
06-14 23:45:52.326: E/AndroidRuntime(6903): 	at android.app.ActivityThread.main(ActivityThread.java:5942)
06-14 23:45:52.326: E/AndroidRuntime(6903): 	at java.lang.reflect.Method.invoke(Native Method)
06-14 23:45:52.326: E/AndroidRuntime(6903): 	at java.lang.reflect.Method.invoke(Method.java:372)
06-14 23:45:52.326: E/AndroidRuntime(6903): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
06-14 23:45:52.326: E/AndroidRuntime(6903): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)

**Comment by KernelCrap** [comment]
You need to include the dependencies in order to build the application.
