### ISSUE TITLE
Android 7

### ISSUE THREAD

**Issue by cpunk** [KernelCrap/android-dlna#4]
After the upgrade to Android 7.0 your app doesn't find the minidlna-server on my RaspberryPie anymore. Are there any known issues with the latest version of Android? My TV has no trouble with this server...

**Comment by knowledgejunkie** [comment]
@cpunk Seeing the same lack of connectivity here, since upgrading to Nougat. No problems testing with BubbleUpnp against the same minidlna server, so issue does seem to be local to this app.

**Comment by KernelCrap** [comment]
I will look into it. Is it only on minidlna or is it all servers?

**Comment by KernelCrap** [comment]
It seems to be a problem with the Cling library. I have updated the library to the latest version and it seems to be working now.
